---
abstract: 'The Perl core test smoke suite'
author:
  - 'H.Merijn Brand <h.m.brand@hccnet.nl>, Nicholas Clark <nick@plum.flirble.org> and Abe Timmerman <abeltje@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Smoke
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: 0.82
  JSON: 0
  LWP::UserAgent: 0
  Test::More: 0
version: 1.53
